# Generated by Django 2.0 on 2018-02-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2000)),
                ('score', models.CharField(default='GOOD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=1000)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.intent')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='intent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.intent'),
        ),
    ]
